import { Geist, Geist_Mono } from "next/font/google";
import { AuthScreen } from "./authpage/AuthScreen.jsx";
import { NavBar } from "../../landing-page/components/navbar/navbar.jsx";
import { Providers } from "./providers.jsx";
import "./globals.css";
const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.className}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NavBar />
        <div className="flex items-center justify-center min-h-screen">
          <AuthScreen />
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
