import { Geist, Geist_Mono } from "next/font/google";
import { NavBar } from "../../landing-page/components/navbar/navbar.jsx";
import { Providers } from "./providers.jsx";
import { Background } from "../../landing-page/components/background.jsx";
import { Toaster } from "react-hot-toast";
import "./globals.css";
const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.className}  h-full antialiased`}>
      <body className="pt-40">
        <Providers>
          <Toaster />
          <Background />
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
